- name: Reload apache
  become: true
  ansible.builtin.service:
    name: "apache2"
    state: reloaded

- name: Restart haproxy
  become: true
  ansible.builtin.service:
    name: haproxy
    state: restarted

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
