- name: reload apache
  become: True
  service:
    name: "apache2"
    state: reloaded

- name: restart haproxy
  become: True
  service:
    name: haproxy
    state: restarted

- name : apt update cache
  become: True
  apt:
    update_cache: yes
